name: 🚀 Deploy via FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      # 💡 Setup tambahan seperti Node.js, PHP, Composer, atau lainnya

      # - name: 📦 Install Dependencies
      #   run: npm install

      # - name: 🏗️ Build Frontend
      #   run: npm run build

      # - name: 🚀 Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_HOST }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./public/build/
      #     server-dir: /htdocs/
